<table width="98%" border="0" cellpadding="4" cellspacing="0">

<tr>
<td align="right" class="pageTitle1" nowrap><h1>&nbsp;&nbsp;about&nbsp;</h1></td>
<td class="pageTitle2"><h1>&nbsp;the evolt.org directory</h1></td>
</tr>

<tr>
<td valign="top" align="right" class="main" nowrap>&nbsp;</td>
<td valign="top" class="main">
The evolt.org directory is a searchable directory containing links covering Web
Design/Development. <a href="/info/guidelines">Suggestions</a> for 
additional links and categories are encouraged, but every link in the directory is 
moderated in order to ensure quality and relevance.
</td>
</tr>

<tr>
<td align="right" class="pageTitle1" nowrap><h1>&nbsp;&nbsp;&nbsp;&nbsp;</h1></td>
<td class="pageTitle2"><h1>&nbsp;future plans</h1></td>
<!-- ## End Page Title -->
</tr>

<tr>
<td valign="top" align="right" class="main" nowrap>&nbsp;</td>
<td valign="top" class="main">
This directory will evolve and improve over time as users suggest sites for
inclusion covering all aspects of web design and development.
<br><br>
If you have any other suggestions, please send an email to the
<a href="mailto:content@lists.evolt.org">evolt.org content team</a>.
</td>
</tr>

<tr>
<td align="right" class="pageTitle1" nowrap><h1>&nbsp;&nbsp;&nbsp;&nbsp;</h1></td>
<td class="pageTitle2"><h1>&nbsp;site credits</h1></td>
<!-- ## End Page Title -->
</tr>

<tr>
<td valign="top" align="right" class="main" nowrap>&nbsp;</td>
<td valign="top" class="main">
Backend code is a modified version of <a 
href="http://webreference.com/perl/xhoo/php1/index.html">phpHoo</a><br>
Search code provided by Michael Wolfe<br>
</td>
</tr>

</table>
<br>