<table width="98%" border="0" cellpadding="4" cellspacing="0">

<tr>
<td align="right" class="pageTitle1" nowrap><h1>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</h1></td>
<td class="pageTitle2"><h1>&nbsp;What to submit</h1></td>
<!-- ## End Page Title -->
</tr>

<tr>
<td valign="top" align="right" class="main" nowrap>&nbsp;</td>
<td valign="top" class="main">
<p>
There are no restrictions to the type of links posted on this site, as long
as they fall beneath the broad umbrella of Web Design/Development.
Suggestions can be to an entire website or a single article.
</p>
<p>
Personal sites will not be accepted, unless they contain significant amounts
of relevant material. There are plenty of other resources that do a better
job of keeping track of personal sites.
</p>
<p>
This directory aims to get web professionals to the information they need
quickly and with minimal hassle. It is hoped that sites linked will also
reflect this policy; well-designed sites with good navigation and plenty of
accurate, useful content are preferred.
</p>
</td>
</tr>

<tr>
<td align="right" class="pageTitle1" nowrap><h1>&nbsp;&nbsp;&nbsp;&nbsp;</h1></td>
<td class="pageTitle2"><h1>&nbsp;How to submit</h1></td>
<!-- ## End Page Title -->
</tr>

<tr>
<td valign="top" align="right" class="main" nowrap>&nbsp;</td>
<td valign="top" class="main">
<p>
Before submitting suggestions, please search the directory to ensure your
link is not already included. If your link is similar to existing entries,
please consider if it offers anything additional not already provided by the
existing links. When writing descriptions for links or categories, please
try to be concise, and consider what information is useful to a user of this
directory. Please mention any technical requirements such as Flash or Java.
</p>
<p>
When adding a link, select the most relevant existing category or create a
new subcategory. Navigate to the selected category then click on "suggest a
link" and fill in the form.
</p>
<p>
Alternatively you can now use this <a href="http://dir.evolt.org/info/bookmarklet">Bookmarklet</a> to quickly suggest sites with just a couple of clicks.
</p>
</td>
</tr>

</table>
<br>


